name: build
on: [push]
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9.0
      - uses: codecov/codecov-action@v1
        with:
          flags: unittests
      - name: Install Requirements
        run: |
          pip install -r requirements.txt
      - name: Run Coverage
        run: |
          pip install coverage
          coverage run run_tests.py
          coverage report
      - run: python setup.py sdist